FROM node:16-alpine

# System updates and dependencies
RUN apk update
RUN apk upgrade --available
RUN apk add vips

# Copy source files
RUN mkdir /srv/strapi
WORKDIR /srv/strapi
COPY ./src ./src
COPY ./config ./config
COPY ./package.json ./package.json
COPY ./public ./public

# Environment configuration
ENV NODE_ENV production
ARG NODE_ENV=${NODE_ENV}

ARG STORAGE_URL
ENV STORAGE_URL=$STORAGE_URL

ARG STORAGE_ACCOUNT 
ENV STORAGE_ACCOUNT=$STORAGE_ACCOUNT

ARG STORAGE_ACCOUNT_KEY
ENV STORAGE_ACCOUNT_KEY=$STORAGE_ACCOUNT_KEY

ARG APP_KEYS
ENV APP_KEYS=$APP_KEYS

ARG STORAGE_CONTAINER_NAME
ENV STORAGE_CONTAINER_NAME=$STORAGE_CONTAINER_NAME

ARG DATABASE_HOST
ENV DATABASE_HOST=$DATABASE_HOST

ARG DATABASE_PASSWORD
ENV DATABASE_PASSWORD=$DATABASE_PASSWORD

ARG DATABASE_USERNAME
ENV DATABASE_USERNAME=$DATABASE_USERNAME

ARG DATABASE_NAME
ENV DATABASE_NAME=$DATABASE_NAME

# Run Strapi
RUN npm i -g yarn --force
RUN yarn install
RUN yarn build
EXPOSE 1337
CMD 