# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - apg-api2

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: https://apgapi2.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_702d6451d2b64a5e8caf7c335f031931 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_15607a9830e24b1dae5bc5cce9a0954d }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: apgapi2.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_702d6451d2b64a5e8caf7c335f031931 }}/apgapi2:${{ github.sha }}
          file: ./Dockerfile
          build-args: STORAGE_ACCOUNT=${{ secrets.STORAGE_ACCOUNT }} 
          build-args: STORAGE_URL=${{ secrets.STORAGE_URL }} 
          build-args: STORAGE_ACCOUNT_KEY=${{ secrets.STORAGE_ACCOUNT_KEY}} 
          build-args: APP_KEYS=${{ secrets.APP_KEYS}} 
          build-args: STORAGE_CONTAINER_NAME=${{secrets.STORAGE_CONTAINER_NAME}} 
          build-args: DATABASE_HOST=${{secrets.DATABASE_HOST}} 
          build-args: DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}} 
          build-args: DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}} 
          build-args: DATABASE_NAME=${{secrets.DATABASE_NAME}}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "apg-api2"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_df15fd3d6c1d40c78c72d6575d79cbbe }}
          images: "apgapi2.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_702d6451d2b64a5e8caf7c335f031931 }}/apgapi2:${{ github.sha }}"
